- app/templates/index.hbs
Needed to have screenreaders recognize WNYC title, which comes from svg. VO didn't read svg title in h2, so included as a span.is-vishidden instead.
> WNYC title

- app/templates/application.hbs
This changes the leaderboard check from `header.rules.homepage` to `eq target.currentRouteName 'index'`, which is what we use elsewhere in that template (https://github.com/nypublicradio/gothamist-web-client/blob/77b9112bee602562c8191e28117a9bdde8a4afd0/app/templates/application.hbs#L6) to determine if we're on the homepage.
> DS-319: Use 'index' ad slot for leaderboard on homepage

- app/styles/app.scss
https://jira.wnyc.org/browse/DS-341
Adds some margin and a width to keep the label aligned.
This css should maybe be moved into pattern lab at some point but we can do that later if it turns out we want to.
> DS-341 home page ad margins

- app/components/ad-tag-leaderboard/template.hbs
- app/components/ad-tag-tall/template.hbs
- app/components/ad-tag-wide/template.hbs
This was a syntax mistake with the ad component setup. The size mapping needs to include arrays of sizes (which are also arrays) I think in the cases where there's only one size, the wrapping array is unnecessary, but i'd rather be consistent than concise here.
> Make sure all ad sizes are requested

- app/breakpoints.js
https://jira.wnyc.org/browse/DS-342
Fixes an issue where the "share" module went vertical at exactly 768px width. This breakpoint, `mediumAndUp`, is only used here:
https://github.com/nypublicradio/gothamist-web-client/blob/11701e4c882d140aec41c27b0845a69d7dbbb321/app/templates/article/index.hbs#L31
> DS-342: Modify 'mediumAndUp' breakpoint to be minimum 769px

- app/components/ad-tag-wide/template.hbs
- Add 250x300 to mobile breakpoint
- Add 250x600 to 750px breakpoint
> Update midpage ad sizes

- app/components/wnyc-block/template.hbs
- app/models/article.js
- app/routes/404.js
- app/styles/app.scss
- app/templates/application.hbs
- add utm params to wnyc stories [DS-335](https://jira.wnyc.org/browse/DS-335)
- fix breadcrumb on on some opinion and analysis stories [DS-112](https://jira.wnyc.org/browse/DS-112)
- thin white line at top of screen (when ads are running; you can't test this until mei flights a takeover) [DS-348](https://jira.wnyc.org/browse/DS-348)
> some post launch fixes

- app/components/ad-tag-inside/component.js
- app/components/ad-tag-inside/template.hbs
- app/components/ad-tag-wide/component.js
- app/modifiers/insert-target.js
- app/templates/article/index.hbs
- tests/acceptance/article-test.js
- tests/integration/components/ad-tag-inside/component-test.js
- tests/integration/modifiers/insert-target-test.js
- yarn.lock
https://jira.wnyc.org/browse/DS-372
This is starting to become a bit of a Rube Goldberg machine... I've been thinking about how to handle this if was starting from scratch but don't have any great ideas yet.
Anyway here's the sequence of events:
1. When navigating from one article to another, the new article loads and the `contentsId` (article id) sent to `insert-target` changes.
2. This triggers `didReceiveArguments` on the `insert-target` modifier, causing it to insert a div into the new article.
3. The `insert-target` modifier then calls the `afterInsert` action (`ad-tag-inside`'s `handleInsert`) with the inserted div.
4. In the `handleInsert` action the `ad-tag-inside` component, updates the wormhole target to the newly inserted div, causing the dfp-ad to be moved into the target div …
> DS-372 Ad re-insertion

- app/routes/article/gallery.js
- app/routes/article/index.js
- package.json
- yarn.lock
`true` is passed in for galleries b/c as long as the argument is truthy,
then NyprOHeader will render the progress bar, and the truthy value
passed into progress bar will fall back to the `body` element, which
works fine for galleries
[DS-310](https://jira.wnyc.org/browse/DS-310)
depends on https://github.com/nypublicradio/nypr-design-system/pull/17
> use new progress bar `target` argument on articles and galleries

- .template-lintrc.js
- app/components/ad-tag-leaderboard/template.hbs
- app/components/ad-tag-tall/template.hbs
- app/components/ad-tag-wide/component.js
- app/components/ad-tag-wide/template.hbs
- app/styles/app.scss
- app/templates/sections.hbs
- package.json
- yarn.lock
Depends on https://github.com/nypublicradio/nypr-ads/pull/9
Depends on https://github.com/nypublicradio/nypr-design-system/pull/16
Use the yielded values from the updated nypr-ads to build the components that represent our different ad tag configurations. We can use the isEmpty status to control whether or not we show the label.  Also remove the standalone label from the sections template.
> Integrated ad labels

- app/components/disqus-comments/component.js
- app/routes/404.js
- app/routes/application.js
- app/templates/article/index.hbs
- app/templates/index.hbs
- app/templates/sections.hbs
- app/templates/tags.hbs
- package.json
- yarn.lock
[DS-380](https://jira.wnyc.org/browse/DS-380)
- adds `memory-scroll` addon to help manage scroll state between transitions
- blank out disqus onReady handler if onReady isn't passed in (otherwise it's still there and will call it anyway)
> scrolling updates

- app/metrics-adapters/chartbeat.js
- app/routes/application.js
- app/routes/article.js
- tests/acceptance/article-test.js
this PR addresses two issues:
- two pageviews fired on initial page load
- missing article metadata from chartbeat's automatic pageview event
so, chartbeat fires a pageview event when its JS library loads. because this fires out of sync with ember routing, it also lacks the correct metadata for when that automatic pageview is an article. 
This PR moves the chartbeat lazy-init into the application route's `transition#finally` callback, which allows us to include anything a child route may set on `metrics.context.pageData`, e.g. title, author and section.
The other side effect of moving init to `finally(...)` is that the chartbeat adapter is not actually initialized when `trackPage` is called in the application's very first `didTransition`, which prevents the duplicate pageviews. It *will* …
> chartbeat fixup

- app/styles/app.scss
[DS-384](https://jira.wnyc.org/browse/DS-384)
> only hide gothamist logo letters on galleries on narrow screens

- app/components/article-block/component.js
- app/components/article-block/template.hbs
- app/components/article-list/template.hbs
- app/components/article-recirc/template.hbs
- app/helpers/imgix-uri.js
- app/index.html
- app/models/article.js
- app/routes/application.js
- app/serializers/gallery.js
- app/styles/app.scss
- app/templates/404.hbs
- app/templates/500.hbs
- app/templates/author-detail.hbs
- app/templates/head.hbs
- app/templates/index.hbs
- app/templates/sections.hbs
- app/templates/tags.hbs
- app/utils/dom-fixer.js
- config/environment.js
- ember-cli-build.js
- package.json
- tests/integration/components/article-block/component-test.js
- tests/unit/helpers/imgix-uri-test.js
- tests/unit/utils/dom-fixer-test.js
- yarn.lock
This PR collects a few optimizations on the way to improve load time.
Imgix is a CDN we can use for specifying image crops. Imgix is configured to pull in images from topics (i.e. gothamist.com) and platypus (i.e. cmsplatypus.gothamist.com); all we need to do is swap out the domain for the correct imigix domain, and add our preferred parameters.
In the interest of "biggest win", this PR only implements imgix for article thumbnails and gallery images (since I was on a roll). Embedded images and image leads can be address in another PR.
You may also notice that the alt tag and aria label attrs have been changed. Pulling in the values off of the parsed body kicked off an image request for any `<img/>` tags encountered, which defeats the purpose of pulling our images through the CDN (the …
> Use imgix to serve images

- app/components/article-block/component.js
- app/components/article-block/template.hbs
- app/components/article-recirc/template.hbs
- app/models/article.js
- app/routes/article.js
- mirage/factories/article.js
- mirage/factories/consts.js
- mirage/factories/index-page.js
- mirage/serializers/article.js
- tests/acceptance/analytics-test.js
- tests/acceptance/article-test.js
- tests/acceptance/gallery-test.js
- tests/acceptance/tags-test.js
- tests/integration/components/article-block/component-test.js
- tests/integration/components/article-recirc/component-test.js
- tests/unit/fixtures/article-fixtures.js
- tests/unit/models/article-test.js
[ticket](https://jira.wnyc.org/browse/CMS-581)
adds a new computed property to the article model. Looks at the new `ancestry` field and grabs the first item in the array that has a `type` value of `standardpages.IndexPage`, which I've set as the const `SECTION_PAGE_TYPE` for reference.
The final commit in this diff is a pretty dumb find/replace for all the places where the old `basename` and `label` keys were used to get at the different category values (category is what we used to call section).
For review, I'd suggest looking at the first four commits only, to reduce the noise: e6ee1a2b0a80bfe18b78519aca0e68a714b844f1...4027b6d423adbadcba4bcebf164f0a76b85e70f6
> derive `section` using new `ancestry` key

- app/controllers/index.js
- app/routes/index.js
- app/templates/index.hbs
- mirage/factories/homepage.js
- mirage/models/homepage.js
- tests/acceptance/homepage-test.js
- tests/unit/controllers/index-test.js
[ticket](https://jira.wnyc.org/browse/CMS-546)
The `BASE_COUNT` const in the index route had to get lowered in order to meet a server requirement. When the server constrain is lifted, that value can be return to `28`.
This adds a `homepage` mirage factory, even though it's not currently used, but may be useful in the future.
> Update homepage for wagtail

- app/components/dismissable-block/component.js
This prevents the product banner from rendering briefly before deciding whether it should be hidden or not.
> CMS-537 product banner update

- app/models/article.js
- app/models/page.js
- app/templates/article.hbs
and also construct a `permalink` value in the article model.
[ticket](https://jira.wnyc.org/browse/CMS-640)
> Use `uuid` for comments

- app/utils/add-comment-count.js
- mirage/factories/article.js
- tests/acceptance/author-detail-test.js
- tests/acceptance/homepage-test.js
- tests/acceptance/section-test.js
- tests/acceptance/tags-test.js
- tests/unit/utils/add-comment-count-test.js
this patch updates the `addCommentCount` utility to use the new computed attr `idForComments` when checking comment counts against the disqus API. The `addCommentCount` will also support  an option for using a different key for lookup, which enables us to safely update the default to the `idForComments` attr.
> use `idForComments` field for comment counts

- app/routes/preview.js
- tests/acceptance/gallery-test.js
- tests/acceptance/preview-test.js
Updates the preview route so it will work correctly for articles with galleries.
> Update preview route to load gallery model

- app/utils/wagtail-api.js
we have a custom polyfill version of Object.fromEntries that should work in edge. It's already imported at the top of this file.
> Hotfix for Edge

- app/models/article.js
- mirage/factories/article.js
- mirage/factories/gallery.js
- tests/acceptance/article-test.js
- tests/acceptance/gallery-test.js
Credit links weren't working on the lead image.
https://jira.wnyc.org/browse/CMS-698
The template was looking for `article.leadImage.image.creditLink`, but `image` properties weren't getting camelCased for the lead image.
This adds some tests and fixes that.
> CMS-698 credit link

- app/components/breaking-news-banner/component.js
- app/components/breaking-news-banner/template.hbs
- app/components/product-banner/component.js
- app/components/product-banner/template.hbs
- app/helpers/get-route-params.js
- app/routes/application.js
- app/routes/index.js
- app/styles/app.scss
- app/templates/application.hbs
- app/templates/index.hbs
- tests/acceptance/article-test.js
- tests/acceptance/author-detail-test.js
- tests/acceptance/section-test.js
- tests/acceptance/tags-test.js
- tests/integration/components/breaking-news-banner/component-test.js
- tests/integration/components/product-banner/component-test.js
Moves product and breaking news banners from home to application route, so we get them on every page.
depends on CSS updates in https://github.com/nypublicradio/pattern-lab/pull/73
https://jira.wnyc.org/browse/CMS-583
> CMS-583 Move banners to every page

- config/environment.js
This isn't really an ideal solution for multisite support as environment variables will start to pile up for different sites (PROD_GOTHAMIST_SITE_ID, PROD_WNYC_SITE_ID, etc...) but for now it lets us differentiate between prod and demo...
> Make siteId configurable with an environment variable

- app/routes/application.js
- app/templates/application.hbs
- package.json
- tests/acceptance/ads-test.js
- yarn.lock
Imports an updated `nypr-ads-htl` that includes code to handle ad teardown on template changes, fixing some issues with multiple ad calls being made.
> CMS-746 Fixes for HTL

- app/components/ad-tag-inside/component.js
- app/components/ad-tag-inside/template.hbs
- app/components/ad-tag-tall/component.js
- app/components/ad-tag-tall/template.hbs
- app/components/ad-tag-wide/component.js
- app/components/ad-tag-wide/template.hbs
- config/environment.js
Adds an config value `LazyLoadAds` that controls whether or not our non-sticky (everything but the wrapper and header slots) ads use lazy loading or not.
This value is turned set to true by the presence of a LAZY_LOAD_ADS environment variable.
This isn't as good as a self-serve solution for adops would be, but for the time being, at least gives us the ability to toggle lazy loading on and off without further code changes.
> Add env var toggle for ad lazy-loading

- app/routes/article.js
- app/routes/gallery.js
- app/routes/preview.js
- app/templates/article.hbs
This disables the recirc module on preview and adds a 'Cache-Control': 'no-cache' header to the preview route.
>  CMS-853 disable recirc on preview

- ember-cli-build.js
Update `nypr-design-system` config to only include Gothamist styles, with no alternative style sheets, when ENV is set to prod.
ENV is an environment variable that's set by CircleCI when we build.
we have two sets of env vars preconfigured in CircleCI, prefixed with PROD_ or DEMO_ and the prefixes get removed as part of the build process. (this should all be in the circle.yml file)
for example, when we're running a prod deploy, the variable PROD_ENV (which has a value of 'prod', as configured in the CircleCI dashboard) will get renamed (copied?) to an environment variable called ENV, which is what i'm reading in the `ember-cli-build.js` here to determine which theme style sheet(s) to include.
> Don't include alternative styles in prod.

- app/components/ad-tag-inside/template.hbs
- app/components/ad-tag-wide/component.js
- app/components/ad-tag-wide/template.hbs
- app/templates/article.hbs
- app/templates/gallery.hbs
- app/templates/tags.hbs
I removed the `showLabel` parameter of the `AdTagWide` component because as far as I can tell there are no use cases for the `ADVERTISEMENT` label to be hidden. This enabled me to also consolidate calls to `NyprAAdLabel` to the `AdTagWide` component, thus removing a potential and/or unreported bug in which the `ADVERTISEMENT` label would display if the ad unit is empty.
> `ADVERTISEMENT` label displays underneath mid-page ads on sections pages (eg, `/foods`)

- yarn.lock
Reverts nypublicradio/gothamist-web-client#188
> Revert "[Security] Bump handlebars from 4.1.0 to 4.7.6"

- package.json
- yarn.lock
rollback nypr-ads-htl to v0.1.5
> rollback nypr-ads-htl

- app/components/disqus-comments/component.js
- app/controllers/application.js
- app/controllers/article.js
- app/controllers/newsletter.js
- app/modifiers/track-impression.js
- app/routes/application.js
- app/styles/app.scss
- app/templates/application.hbs
- app/templates/article.hbs
- app/templates/newsletter.hbs
- app/templates/tags.hbs
- app/utils/track-event.js
- package.json
- tests/integration/modifiers/track-impression-test.js
- tests/unit/utils/track-event-test.js
- yarn.lock
Implements the [NTG spec](https://newsinitiative.withgoogle.com/training/datatools/ntg?id=UA-65258-1&platform=analytics&content=user-engagement) for the following events
- Newsletter Signup
- Newsletter Signup Prompt Impressions
- Social Sharing
- Comments
**Newsletter Signup Prompt Impressions**
The most involved implementation here by far is the signup impressions.
I added an impression tracking modifier that we can add to a wrapper div around any component. It uses IntersectionObserver to track when it becomes viewable. 
Since divs and components can stick around when navigating, it listens for a 'routeChange' event on window to reset the viewed state, so we can track another impression on each new route.  'routeChange' is a completely artificial event that I'm firing manually from the …
> GOTH-3 Google News Tagging Guide (NTG) spec for Google News Initiative (GNI)

- app/components/disqus-comments/component.js
- app/controllers/article.js
- app/templates/article.hbs
Update code for tracking new comments. This moves the callback out of the disqus component and lets the user of the component handle the tracking.
> Update comment tracking

- app/routes/tags.js
- mirage/config.js
- mirage/factories/tagpage.js
- mirage/models/tagpage.js
- public/robots-demo.txt
- tests/acceptance/homepage-test.js
- tests/acceptance/tags-test.js
Updates the head metadata properties with title, description, and image from social override fields on the tag page, if available.
Copied in some mirage testing stuff from some in progress PRs to make writing the test easeir
> GOTH-53 Update head metadata with social overrides from tag page API

- app/routes/tags.js
- mirage/config.js
- mirage/factories/tagpage.js
- mirage/models/tagpage.js
- package.json
- public/robots-demo.txt
- tests/acceptance/homepage-test.js
- tests/acceptance/tags-test.js
- yarn.lock
- previously we weren't getting the tag name at all, just generating from the url slug
- instead of making a new API call to the snippets/tags api, we get the tag name out of the tags field of the first article
- also updated a css rule that made this heading always lowercase: https://github.com/nypublicradio/nypr-design-system/pull/183
Before merging this:
> GOTH-59 use capitalization from tag's name field instead of all lowercase on tag page heading

- tests/acceptance/head-test.js
Potential fix for a flaky test that sometimes caused our circleCI builds to fail.
It looks like a typo in this test created an invalid CSS selector string. It doesn't seem to cause a js exception when i run it on it's own and I don't understand at all why this sort of thing would be non-deterministic, but nevertheless it's close enough to the problematic test that i'm very suspicious.
Reran it a few times on circle to see what happens and didn't get a failure, but because the issue was intermittent there's no way to know for sure if this fixes it, unless it doesn't. Seems like a fix worth merging regardless.
> possible fix for canonical url test?

- config/environment.js
Right now we're getting lots of sentry errors reports from ads, external analytics scripts, chrome extensions, etc. This config change will cut down on a big chunk of the noise by limiting reports to only errors from our scripts.
> Whitelist sentry error reports to only scripts served from our domains
