app/components/ad-tag-wide/template.hbs, app/templates/article/gallery.hbs, config/environment.js, package.json, tests/acceptance/gallery-test.js, yarn.lock
https://jira.wnyc.org/browse/DS-218
=> Add ad slots to gallery pages

fastboot.js, package.json, yarn.lock
depends on releasing nypublicradio/nypr-fastboot#9
[DS-149](https://jira.wnyc.org/browse/DS-149)
=> don't use UA strings for health checks

app/templates/sections.hbs, app/templates/tags.hbs
https://jira.wnyc.org/browse/DS-279
https://jira.wnyc.org/browse/DS-280
https://jira.wnyc.org/browse/DS-322
=> Add ad slots to tag and section pages

nginx/nginx.conf
location blocks for /assets_c and /attachments that proxy to the legacy frontend ELB
=> location blocks for images in daffy release

app/controllers/article/index.js, app/routes/article.js, app/routes/article/index.js, app/templates/article/index.hbs, config/environment.js, tests/acceptance/article-test.js, yarn.lock
[DS-229](https://jira.wnyc.org/browse/DS-229)
=> Donate Tout Cookies

app/templates/index.hbs
DS-289 part 2
Removed one class tag as the hidden element was adding extra space
=> Aria more results message on homepage

app/components/article-block/template.hbs, app/models/article.js, app/utils/dom-fixer.js, yarn.lock
related to https://github.com/nypublicradio/nypr-design-system/pull/9
This creates an alt label from the image caption in the article model and strips out html (to remove links).
=> Accessible Alt Attributes

app/styles/app.scss
Support 600 height ads in absolute positioned slots
=> Fix ads overlapping content on article pages

nginx/nginx.conf
also condensing the locations into a single block
=> adding /images as a proxy to the old FE LB

package.json, yarn.lock
depends on https://github.com/nypublicradio/nypr-design-system/pull/14
=> for [DS-367]

app/routes/article/index.js, package.json, yarn.lock
moves calls to twitter JS API into article body component
depends on nypublicradio/nypr-design-system#13
=> more twitter embed fixes

app/templates/index.hbs
related to this PR at nypr-design-system: https://github.com/nypublicradio/nypr-design-system/pull/7
=> Newsletter Module Accessibility

package.json, yarn.lock
[DS-257](https://jira.wnyc.org/browse/DS-257)
depends on nypublicradio/nypr-design-system#22
=> some font tweaks

app/routes/staff.js, app/templates/staff.hbs, yarn.lock
[DS-327](https://jira.wnyc.org/browse/DS-327)
~depends on nypublicradio/pattern-lab#57~
=> remove "articles" link from non-authors

app/templates/application.hbs, yarn.lock
nypublicradio/nypr-design-system#21
[DS-360](https://jira.wnyc.org/browse/DS-360)
=> open menu at full viewport height

app/controllers/index.js, app/templates/index.hbs, yarn.lock
[DS-261](https://jira.wnyc.org/browse/DS-261)
=> adds donation ask using box banner component

app/components/article-block/template.hbs, app/models/article.js, package.json, yarn.lock
depends on nypublicradio/nypr-design-system#12
[DS-357](https://jira.wnyc.org/browse/DS-357)
=> add video icons and update design system

app/routes/index.js, app/templates/index.hbs, mirage/config.js, tests/acceptance/homepage-test.js
[DS-407](https://jira.wnyc.org/browse/DS-407)
=> support @main@sponsor ads

app/routes/article.js, app/routes/index.js, app/templates/head.hbs
[DS-374](https://jira.wnyc.org/browse/DS-374)
[DS-375](https://jira.wnyc.org/browse/DS-375)
=> seo title updates

app/controllers/article/gallery.js, package.json, tests/acceptance/article-test.js, yarn.lock
Depends on: https://github.com/nypublicradio/nypr-design-system/pull/19
https://jira.wnyc.org/browse/DS-340
- Add UTM parameters to gallery share metadata
=> DS-340 Add UTM parameters to links shared from gallery

.eslintrc.js, exportist/dom-fixer.js, exportist/exportist.js, exportist/lib/dom-fixer.js, package.json, yarn.lock
[CMS-605](https://jira.wnyc.org/browse/CMS-605)
[CMS-589](https://jira.wnyc.org/browse/CMS-589)
=> exportist script

app/adapters/page.js, app/routes/index.js, tests/acceptance/homepage-test.js, tests/unit/adapters/page-test.js
a few updates to make polymorphism and system messages slightly safer
=> Polymorphism and safety

app/components/breaking-news/component.js, app/components/breaking-news/template.hbs, app/routes/index.js, app/templates/index.hbs, package.json, tests/acceptance/homepage-test.js, tests/integration/components/breaking-news/component-test.js, yarn.lock
[DS-260](https://jira.wnyc.org/browse/DS-260)
depends on nypublicradio/nypr-design-system#24
and ~nypublicradio/pattern-lab#59~
=> support for breaking news banner

app/components/article-block/component.js, app/components/article-block/template.hbs, app/components/article-body/image/template.hbs, app/controllers/article.js, app/controllers/gallery.js, app/models/article.js, app/models/gallery.js, app/routes/article.js, app/serializers/gallery.js, app/templates/article.hbs, app/utils/wagtail-api.js, config/environment.js, mirage/factories/article.js, mirage/factories/gallery.js, tests/acceptance/gallery-test.js, tests/integration/components/article-block/component-test.js, tests/integration/components/article-body/component-test.js, tests/unit/models/article-test.js, tests/unit/serializers/gallery-test.js, tests/unit/utils/wagtail-api-test.js, yarn.lock
[CMS-620](https://jira.wnyc.org/browse/CMS-620)
client-side updates to use fully-serialized images and associated metadata
=> use fully-serialized image objects

app/components/article-body/block-quote/component.js, app/components/article-body/block-quote/template.hbs, app/components/article-body/pull-quote/component.js, app/components/article-body/pull-quote/template.hbs, tests/integration/components/article-body/component-test.js, yarn.lock
[ticket](https://jira.wnyc.org/browse/CMS-615)
=> Support blockquotes and pull quotes in article body

app/components/article-block/template.hbs, app/components/article-recirc/component.js, app/components/article-recirc/template.hbs, app/templates/article.hbs, mirage/factories/article.js, tests/acceptance/article-test.js, tests/integration/components/article-recirc/component-test.js, yarn.lock
Updates the `<ArticleRecirc/>` component to show "recent" articles instead of "related"
[ticket](https://jira.wnyc.org/browse/CMS-619)
=> Article Recirc (with fixed diff)

app/routes/article.js, app/routes/gallery.js, app/templates/head.hbs
[ticket](https://jira.wnyc.org/browse/CMS-639)
=> hide articles/galleries from robots if show_on_index_listing is false

app/routes/application.js
https://jira.wnyc.org/browse/CMS-627
=> Update RSS link to new feed url

app/adapters/page.js, app/routes/preview.js, app/serializers/page.js
based on the guides, all we need to enable polymorphism is to [add a `type` key to the payload](https://guides.emberjs.com/release/models/relationships/#toc_polymorphism) that corresponds to an ember-data model, and ED will take care of the rest.
ping @walsh9
=> enable polymorphism on preview route

app/controllers/search.js, app/serializers/application.js, app/serializers/article.js, app/templates/search.hbs, mirage/config.js, mirage/utils.js, tests/acceptance/search-test.js
[ticket](https://jira.wnyc.org/browse/CMS-629)
we've got a component in use on all our listing pages, e.g. `section`, `tag`, the homepage, etc. I'm re using it here on the search template.
=> Paginate search results

app/routes/gallery.js
[CMS-672](https://jira.wnyc.org/browse/CMS-672)
=> pass in correct value for slide image preview

app/adapters/page.js, app/serializers/page.js
https://jira.wnyc.org/browse/CMS-687
Fixes two issues related to with previewing a brand new unsaved page
=> CMS-687 preview

app/models/article.js, app/templates/article.hbs, mirage/factories/article.js, tests/acceptance/article-test.js
Needs nypublicradio/cms#242 to work but won't break anything without it.
=> CMS-575 lead image link

app/components/ad-tag-wide/template.hbs, app/templates/gallery.hbs, tests/acceptance/gallery-test.js
https://jira.wnyc.org/browse/DS-452
=> DS-452 Update gallery ad cadence

app/models/article.js, mirage/factories/article.js, package.json, tests/acceptance/article-test.js, yarn.lock
Display the related author's contributing org as part of the byline
Depends on:
https://github.com/nypublicradio/nypr-design-system/pull/36
https://github.com/nypublicradio/cms/pull/295
TODO:
=> CMS-653 contributing org in byline

app/templates/article.hbs, app/templates/index.hbs, package.json, yarn.lock
- Change icon and copy for donation module on home page and article pages
TODO:
=> DS-550 donation module

app/templates/application.hbs
https://jira.wnyc.org/browse/DS-541
=> Just Craig thanks

package.json, yarn.lock
Update `nypr-design-system` to `3.0.0-alpha2`
=> Font scales independent of type

ember-cli-build.js, package.json, yarn.lock
https://github.com/jeffjewiss/ember-cli-postcss
=> Add PostCSS / Autoprefixer

app/components/product-banner/template.hbs, package.json, yarn.lock
- Add mod-donate class to product marketing banner button
=> DS-767 Make the donate button on the product marketing banner red

package.json, yarn.lock
Need to update demo to use the new design system release
=> update design system

app/routes/application.js, tests/acceptance/analytics-test.js
I added then `optimize.activate` event to make Optimize work in a Single Page App.
=> GT-121 optimize.activate

app/components/link-to/component.js, app/routes/application.js, app/styles/app.scss, app/templates/application.hbs, package.json, tests/acceptance/analytics-test.js, yarn.lock
When is https://jira.wnyc.org/browse/DS-859 completed, I will need to change `url: '/newsletter'` to `route: 'newsletter'`
=> Add `Newsletter` link to top nav and side menu

package.json, yarn.lock
Update design system version
Not much should change visibly, hopefully any changes are fixes.
- Header nav links changed back to bold
- The dashed line between lead image and share icons should return
=> DS-828 token updates

app/components/product-banner/template.hbs, app/templates/application.hbs, app/templates/author-detail.hbs, app/templates/index.hbs, app/templates/search.hbs, app/templates/sections.hbs, app/templates/tags.hbs, package.json, yarn.lock
- Replace all uses of `NyprAButton` with `Button` component
- Update classes to use the theme's modifier classes
Todo before merge:
=> DS-929 gothamist button theming

app/app.js, config/environment.js, package.json, tests/test-helper.js, yarn.lock
Implement sentry for ember following instructions here: https://docs.sentry.io/platforms/javascript/guides/ember/
This also requires updating the sentry library used by our fastboot middleware in nypr-fastboot.
=> GOTH-1 Implement Sentry for ember

app/modifiers/track-scroll-depth.js, app/templates/article.hbs, tests/integration/modifiers/track-scroll-depth-test.js
Track scroll depth events on articles
=> DS-475 Scroll Depth Tracking

app/components/product-banner/template.hbs, app/controllers/index.js, app/styles/app.scss, app/templates/application.hbs, app/templates/article.hbs, app/templates/index.hbs, package.json, yarn.lock
Add events are added to all membership modules with following numbering:
Header donate button: 1
Sidemenu donate button: 2
Article page flyout (article title): 3
Homepage banner: 4
Product marketing banner: 5
Depends on https://github.com/nypublicradio/nypr-design-system/pull/180
=> GOTH-32 Membership modal tracking

app/routes/preview.js, app/routes/tags.js, mirage/config.js, tests/acceptance/preview-test.js
https://jira.wnyc.org/browse/CMS-634
=> Adds preview functionality for Curated Tag Pages

public/ads.txt
https://jira.wnyc.org/browse/GOTH-77
=> updated ads.txt file per Rachel
